[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#[rpc_endpoints]
#optimism = "${OPTIMISM_RPC_URL}"
#base = "${BASE_RPC_URL}"
#
#[etherscan]
optimismGoerli = "https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
baseGoerli = "https://base-goerli.g.alchemy.com/v2/JsSsdQeYjg9VZK7Dp2kjAxtFM2Dwa4dv"



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
